name: Deploy images

on:
  push:
    tags:
      - '*'

env:
  OPERATOR_SDK_VERSION: v0.18.1
  KUBECONFIG: /tmp/kubeconfig
  IMAGE_NAME: quay.io/mittwald/kubeav
  REGISTRY_URL: quay.io/mittwald

jobs:
  deploytagged:
    name: Deploy Tagged Image
    runs-on: ubuntu-latest
    needs: ['test', 'build']
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go

      - name: Registry Login
        run: docker login -u "${{ secrets.QUAY_IO_USER }}" -p "${{ secrets.QUAY_IO_TOKEN }}" "${REGISTRY_URL}"

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install operator-sdk
        run: sudo curl -L -o /usr/local/bin/operator-sdk "https://github.com/operator-framework/operator-sdk/releases/download/${OPERATOR_SDK_VERSION}/operator-sdk-${OPERATOR_SDK_VERSION}-x86_64-linux-gnu" && sudo chmod +x /usr/local/bin/operator-sdk

      - name: Build tagged image
        run: operator-sdk build "$IMAGE_NAME:latest" --go-build-args "-ldflags -X=version.Version=${GITHUB_REF##*/}"

      - name: Tag versioned image
        run: |
          docker tag "$IMAGE_NAME:latest" "$IMAGE_NAME:${GITHUB_REF##*/}"
          docker tag "$IMAGE_NAME:latest" "$IMAGE_NAME:${${GITHUB_REF##*/}%%.*}"

      - name: Push images
        run: |
          docker push "$IMAGE_NAME:latest"
          docker push "$IMAGE_NAME:${GITHUB_REF##*/}"
          docker push "$IMAGE_NAME:${GITHUB_REF##*/}"
          docker push "$IMAGE_NAME:${${GITHUB_REF##*/}%%.*}"

      - name: Bump Chart Version
        run: bash ./scripts/bump-app-version.sh publish "${GITHUB_REF##*/}" "${{ secrets.RELEASE_USER_TOKEN }}"